name: built_redux_thunk
version: 0.5.0
description:
   Thunks for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_thunk
dependencies:
  built_redux: ">=6.1.1 <8.0.0"
  built_value: ^5.1.0

dev_dependencies:
  built_collection: ^3.0.0
  build_runner: ^0.9.0
  built_value_generator: ^5.1.0
  source_gen: ^0.8.0
  test: ^1.0.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

environment:
  sdk: '>=2-0-0-dev <2.0.0'
