name: built_redux_thunk
version: 0.5.1
description:
   Thunks for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_thunk
dependencies:
  built_redux: ">=6.1.1 <8.0.0"
  built_value: ">=4.1.0 <7.0.0"

dev_dependencies:
  built_collection: ^3.0.0
  build_runner: ^0.10.0
  built_value_generator: ^6.0.0
  source_gen: ^0.9.0
  test: ^1.0.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

environment:
  sdk: '>=2.0.0-dev <3.0.0'